import type { Pregunta } from "./tipos";

// Seed de las 15 preguntas. Editable a mano aquí o desde el panel /admin
// (que guarda una copia en la BD). Marca de respuesta(s) correcta(s) en
// `correctas` / `correcto` / `aceptadas`.
export const PREGUNTAS_SEED: Pregunta[] = [
  {
    id: "p1",
    tipo: "bienvenida",
    enunciado: "¡Competencia del Baby Shower!",
    subtitulo: "Escanea el QR o entra con el PIN para jugar 🍄",
    activa: true,
    timer: 0,
    puntaje: 0,
  },
  {
    id: "p2",
    tipo: "opcion",
    enunciado: "¿Cuál es el mes esperado de nacimiento?",
    activa: true,
    timer: 20,
    puntaje: 1000,
    opciones: [
      { id: "a", texto: "Junio" },
      { id: "b", texto: "Julio" },
      { id: "c", texto: "Agosto" },
      { id: "d", texto: "Octubre" },
    ],
    correctas: ["d"],
  },
  {
    id: "p3",
    tipo: "opcion",
    enunciado: "¿Dónde se conocieron Melani y Vicente?",
    activa: true,
    timer: 20,
    puntaje: 1000,
    opciones: [
      { id: "a", texto: "Chile" },
      { id: "b", texto: "China" },
      { id: "c", texto: "Malasia" },
      { id: "d", texto: "Singapur" },
    ],
    correctas: ["d"],
  },
  {
    id: "p4",
    tipo: "multiple",
    enunciado: "¿Cuándo se enteraron del embarazo?",
    subtitulo: "Hay dos respuestas correctas 👀",
    activa: true,
    timer: 20,
    puntaje: 1000,
    opciones: [
      { id: "a", texto: "0 a 28 días" },
      { id: "b", texto: "+1 mes" },
      { id: "c", texto: "+2 mes" },
      { id: "d", texto: "+3 mes" },
    ],
    correctas: ["a", "d"],
  },
  {
    id: "p5",
    tipo: "slider",
    enunciado: "¿Cuántas semanas tiene Meli hoy?",
    activa: true,
    timer: 20,
    puntaje: 1000,
    min: 0,
    max: 44,
    correcto: 35,
    unidad: "semanas",
  },
  {
    id: "p6",
    tipo: "opcion",
    enunciado: "¿Qué signo será? (según la fecha esperada)",
    activa: true,
    timer: 20,
    puntaje: 1000,
    opciones: [
      { id: "a", texto: "Leo" },
      { id: "b", texto: "Libra" },
      { id: "c", texto: "Virgo" },
      { id: "d", texto: "Cáncer" },
    ],
    correctas: ["d"],
  },
  {
    id: "p7",
    tipo: "opcion",
    enunciado: "¿Dónde fue la concepción?",
    activa: true,
    timer: 20,
    puntaje: 1000,
    opciones: [
      { id: "a", texto: "Singapur" },
      { id: "b", texto: "Chile" },
      { id: "c", texto: "Malasia" },
      { id: "d", texto: "Indonesia" },
    ],
    correctas: ["d"],
  },
  {
    id: "p8",
    tipo: "opcion",
    enunciado: "¿Cuándo se enteró la abuela Shirley?",
    activa: true,
    timer: 20,
    puntaje: 1000,
    opciones: [
      { id: "a", texto: "Enero" },
      { id: "b", texto: "Octubre" },
      { id: "c", texto: "Noviembre" },
      { id: "d", texto: "Diciembre" },
    ],
    correctas: ["d"],
  },
  {
    id: "p9",
    tipo: "opcion",
    enunciado: "¿Dónde nacerá el bebé? (idealmente)",
    activa: true,
    timer: 20,
    puntaje: 1000,
    opciones: [
      { id: "a", texto: "Sótero del Río" },
      { id: "b", texto: "Clínica Las Condes" },
      { id: "c", texto: "Marcoleta UC" },
      { id: "d", texto: "Santa María" },
    ],
    correctas: ["c"],
  },
  {
    id: "p10",
    tipo: "opcion",
    enunciado: "¿Cómo se llama la primera caca?",
    activa: true,
    timer: 20,
    puntaje: 1000,
    opciones: [
      { id: "a", texto: "Meconio" },
      { id: "b", texto: "Bilirrubina" },
      { id: "c", texto: "Calostro" },
      { id: "d", texto: "Vérnix" },
    ],
    correctas: ["a"],
  },
  {
    id: "p11",
    tipo: "opcion",
    enunciado: "¿Fecha de hoy? ¡Rápido!",
    subtitulo: "Timer corto ⚡",
    activa: true,
    timer: 10,
    puntaje: 1000,
    opciones: [
      { id: "a", texto: "11/06/2026" },
      { id: "b", texto: "23/06/2026" },
      { id: "c", texto: "13/06/2026" },
      { id: "d", texto: "14/06/2026" },
    ],
    correctas: ["c"],
  },
  {
    id: "p12",
    tipo: "opcion",
    enunciado: "¿Significado de calostro?",
    activa: true,
    timer: 20,
    puntaje: 1000,
    opciones: [
      { id: "a", texto: "Leche descremada" },
      { id: "b", texto: "Parte de la placenta" },
      { id: "c", texto: "Suero lácteo" },
      { id: "d", texto: "Primera leche" },
    ],
    correctas: ["d"],
  },
  {
    id: "p13",
    tipo: "opcion",
    enunciado: "¿Qué elemento importante abunda en el calostro?",
    activa: true,
    timer: 20,
    puntaje: 1000,
    opciones: [
      { id: "a", texto: "Anticuerpos" },
      { id: "b", texto: "Almidón" },
      { id: "c", texto: "Vitamina A" },
      { id: "d", texto: "Vitamina K" },
    ],
    correctas: ["a"],
  },
  {
    id: "p14",
    tipo: "texto",
    enunciado: "Nombre de pila de la abuela paterna",
    subtitulo: "Escríbelo, no importan tildes ni mayúsculas",
    activa: true,
    timer: 20,
    puntaje: 1000,
    aceptadas: ["Shirley"],
  },
  {
    id: "p15",
    tipo: "opcion",
    enunciado: "Nombre completo de Octavio",
    activa: true,
    timer: 20,
    puntaje: 1000,
    opciones: [
      { id: "a", texto: "Octavio Parejas Miranda" },
      { id: "b", texto: "Octavio Pareja Moya" },
      { id: "c", texto: "Octavio Pareja Miranda" },
      { id: "d", texto: "Octavio Parejas Moya" },
    ],
    correctas: ["c"],
  },
];
